build: false

matrix:
  fast_finish: true

platform:
  - x64

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA_DIRNAME: C:\Miniconda2-x64

init:
  - ECHO %PYTHON_VERSION% %MINICONDA_DIRNAME%

install:
  - cmd: set "PATH=%MINICONDA_DIRNAME%;%MINICONDA_DIRNAME%\\Scripts;%PATH%"

  - cmd: conda config --set always_yes true
  - cmd: conda update --quiet conda
  - cmd: conda info --all
  - cmd: conda create --quiet --name conda-env-%PYTHON_VERSION% python=%PYTHON_VERSION% --file requirements-conda.txt
  - cmd: activate conda-env-%PYTHON_VERSION%
  - cmd: python setup.py develop

test_script:
  - ps: |
      py.test --cov=./segmentator
