build: false

matrix:
  fast_finish: true

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x" # currently 2.7.9
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - "python -m pip install -U pip"
  - "pip install msvc_runtime"
  - "pip install -r requirements.txt"
  - "python setup.py develop"

test_script:
  - py.test --cov=./segmentator
