image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "python setup.py develop"

test_script:
  - py.test --cov=./segmentator
